<?php

namespace Kbh\GestionCongesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends EntityRepository
{
     public function findAbsencesExceptionnelles(){
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.valideurEnCours = :superviseur')
           ->setParameter('superviseur', $superviseurConnecte)
               ->andWhere('d.estCloture = 0') 
           ->orderBy('d.dateDemande', 'DESC');


        return $qb->getQuery()->getResult();
    }
}
