<?php

namespace Kbh\GestionCongesBundle\Entity;

/**
 * ImportSalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportSalarieRepository extends \Doctrine\ORM\EntityRepository
{
}
