<?php

namespace Kbh\GestionCongesBundle\Entity;

/**
 * ImportUniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportUniteRepository extends \Doctrine\ORM\EntityRepository
{
}
