<?php

namespace Kbh\GestionCongesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogUpdateMensuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogUpdateMensuelRepository extends EntityRepository
{
    public function findMonthUpdate($month){
        $qb = $this->createQueryBuilder('s');
        //Récupération de l'année
        $today = new \DateTime();
        $year = date('Y', $today->getTimestamp());
        $day = $year.'-'.$month.'-15';
        
        //Création des dates intervalles
        $datedebut = $year.'-'.$month.'-01';
        $dateFin = $year.'-'.$month.'-28';
        
        $qb->where(':day BETWEEN :debut AND :fin')
           ->setParameter('debut', $datedebut)
           ->setParameter('fin', $dateFin)
           ->setParameter('day', $day);

        return $qb->getQuery()->getResult();
    }
}
