<?php

namespace Kbh\GestionCongesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganigrammeUniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganigrammeUniteRepository extends EntityRepository
{
    public function unitsAttached($unite){
        $qb = $this->createQueryBuilder('o');

        $qb->where('o.uniteSuivante1 = :unite')
		   ->orWhere('o.uniteSuivante2 = :unite')
		   ->orWhere('o.uniteSuivante3 = :unite')
           ->setParameter('unite', $unite);

        return $qb->getQuery()->getResult();
    }
    
    public function findUnitsAttached($unite){
        $qb = $this->createQueryBuilder('o');

        $qb->where('n.uniteSuivante1 = :unite')
            ->orWhere('n.uniteSuivante2 = :unite')  
            ->orWhere('n.uniteSuivante3 = :unite')
           ->setParameter('unite', $unite) 
//           ->setMaxResults(5)
           ->orderBy('n.nom', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
