<?php

namespace Kbh\GestionCongesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarieRepository extends EntityRepository
{
//    public function findOneByUser(\Kbh\UserBundle\Entity\User $user){
//        $em = $this->getDoctrine()->getManager();
//
//        $salarie = $em->getRepository('KbhGestionCongesBundle:Salarie')->findOneByUser($user->getId());
//        
//        return $salarie;
//    }
    
     public function findAllCollaborateurs($superviseurConnecte){
        $qb = $this->createQueryBuilder('s');

        $qb->where('s.superviseur = :superviseur')
           ->setParameter('superviseur', $superviseurConnecte)
           ->orderBy('s.nom', 'ASC');


        return $qb->getQuery()->getResult();
    }
    
    public function findSalariesActifs(){
        $qb = $this->createQueryBuilder('s');
        $statut = 'actif';

        $qb->where('s.actif = : statut')
           ->andWhere('statut', $statut)     
           ->orderBy('s.nom', 'ASC');

        return $qb->getQuery()->getResult();
    }
    
}
